FLASK_APP=app
FLASK_ENV=development
SQLALCHEMY_DATABASE_URI=sqlite:////tmp/test.db
SQLALCHEMY_TRACK_MODIFICATIONS=False
SECRET_KEY=secret
REDIS_URL=redis://redis:6379/0
CACHE_TYPE=redis
CACHE_DEFAULT_TIMEOUT=300