version: '3.7'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.7
#    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
    ports:
      - 3306:3306
